version: '3'
services:
  node-app:
    build: 
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env
    command: npm run dev
  
  mongo:
    image: mongo
    env_file:
      - ./.env
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis:3
    # env_file:
    #   - ./.env

volumes:
  mongo-db: