version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app

  node-app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    env_file:
      - ./.env
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    env_file:
      - ./.env

volumes:
  mongo-db: